### ISSUE TITLE
REI console errors, and fatal when viewing recipes

### ISSUE THREAD

**Issue by Disketaa** [null2264/CobbleGen#35]
![image](https://github.com/null2264/CobbleGen/assets/76956762/9829deab-ea37-4c61-a2bc-79639040f171)

**Comment by null2264** [comment]
Same issue as #34

**Comment by Disketaa** [comment]
Thanks for the fast fix! But now REI simply doesn't show cobblestone generator category :c

**Comment by null2264** [comment]
That's weird, the fix shouldn't affect that... I'll look into it later today

**Comment by null2264** [comment]
Weird, it works in my PC... maybe try reinstalling both REI and CobbleGen? also delete the CobbleGen config file just to make sure it's not caused by empty cobblestone gens configuration. If the issue persist, feel free to open a new issue.
![image](https://github.com/null2264/CobbleGen/assets/46041660/6feb6688-ecb8-418a-9d64-35c6b87b39f9)
