### ISSUE TITLE
suggestion on future update

### ISSUE THREAD

**Issue by cold233** [null2264/CobbleGen#9]
I'm using this mod on 1.18.2 with Create and Twilight Forest, and I found an interesting phenomenon: unlike other mods, whose mineral blocks are separated blocks, mineral blocks in Twilight Forest are all the same block with different block state (twilightforest:block_storage). When trying to use this block to generate andesite in basalt way, CobbleGen didn't work. I doubt if I write the configuration file correct, but after checking it multiple times, I made sure that the config work just fine with other blocks. Then I changed the config to make twilightforest:block_storage to generate in basalt way, and it worked but didn't generate any block(the lava produced the sound of solidification repeatedly but no block appeared there). Then I thought it might be CobbleGen can't handle blocks with block states. Maybe adding this feature to the mod will be a good idea for the future update.

**Comment by null2264** [comment]
I currently don't have a stable connection, so I can't work on this mod for a while... But I'll see what I can do about it, probably gonna take a while since I'm also not familiar with Twilight Forest.

**Comment by cold233** [comment]
Thanks a lot. Your mod really helped me a lot, looking forward to your future work.

**Comment by null2264** [comment]
Can you provide me with which version of Twilight Forest you were playing on, and which block you were trying to generate? Since I can't seem to reproduce this issue

**Comment by cold233** [comment]
> 

sure, I will also provide some other adittion information in case you need it.
TW version : 4.1.268 
minecraft version: 1.18.2
fabric version:0.14.9
cobblegen : v1.11b36
java version : 18
other mod:
reese_sodium_options 1.4.6
Xaeros_minimap 1.28.0
not_enough_animations 1.6.0
first_person_fabric 2.1.2
creat_fabric 0.5.0e
minihud 0.22.0
majobroom 1.2.1
sodium_extra 0.4.7
sodium 0.4.1
litematica 0.11.3
indium 1.0.6
BBoutlineReloaded 2.5
architctury 4.6.77
cloth_config 6.2.62
fabric-api 0.59.0
carpet 1.4.69
iris_flywheel_compat 0.1.5
iris 1.3.1
malilib 0.12.1
RoughlyEnoughItems 8.3.519
trinkets 3.3.1
tweakeroo 0.13.3

as for you can't finding the block, I will give you a link of the TW official wiki of that block:
http://benimatic.com/tfwiki/index.php?title=Block_of_Ironwood
as you can see, this block dosen't show as "block storage" in game menu, it shows as numerous of different blocks depending on its value(for example, block of ironwood's value is 0), and block of ironwood is the block  I initially found this bug.
thanks a lot for your reply, and I'm sorry for I didn't provide the full information because i didn't think this is a bug.

**Comment by null2264** [comment]
I see... Those blocks have been changed on the modern Minecraft (especially 1.18.2) releases following modern [Minecraft IDs flattening](https://minecraft.fandom.com/wiki/Java_Edition_1.13/Flattening) and that wiki is not updated to reflect those changes, on 1.18.2 specifically they've split block storage entirely in the code.

Note that you could enable "Advanced Tooltip" by pressing F3 + H to find the block's actual ID. Block of Ironwood's ID is now `twilightforest:ironwood_block` instead of `twilightforest:block_storage`.

I tried generating these blocks (which previously fall under block_storage ID) in Basalt way and it seems to be working. If you still couldn't generate it maybe try updating CobbleGen to [v2.1](https://modrinth.com/mod/cobblegen/version/2.1).

![image](https://user-images.githubusercontent.com/46041660/202680112-5b297dfb-09b3-481b-8e9c-ee1db1da1404.png)

**Comment by cold233** [comment]
thanks a lot! I'll check it in game.
